#!/usr/bin/env bash

DBG=0
DEF=0

# get os
if [ -f /etc/redhat-release ]; then
  export LXTYPE=RHEL
elif [ -f /etc/SuSE-release ]; then
  export LXTYPE=SUSE
elif [ -f /etc/SUSE-brand ]; then
  export LXTYPE=SUSE
elif [ -f /etc/debian_version ]; then
  export LXTYPE=DEBIAN
elif [ -f /etc/gentoo-release ]; then
  export LXTYPE=GENTOO
fi

if [ $LXTYPE == "RHEL" ]; then
# RHEL variant -
  DEF=1
  if [ -f /etc/os-release ]; then
    RHID=`grep '^ID=' /etc/os-release|awk -F= '{ print $2 }' | tr -d \"`
    RREL=`grep '^VERSION_ID=' /etc/os-release | awk -F= '{ print $2 }' | tr -d \"`
  else
    # looks like an older release
    RAWVER=`cat /etc/redhat-release`
    RREL=`echo $RAWVER|tr -d [A-Za-z\(\)]|tr -d " "|awk -F\. ' { print $1 }'`
    RHID=`echo $RAWVER|tr -d [0-9\(\)]|awk '{print $1 }'| tr [A-Z] [a-z]`
  fi
  if [ $DBG -ne 0 ]; then
    echo
    echo "### DEBUG ###"
    echo "redhat-release: $RAWVER"
    echo "VERSION_ID from os-release: $RHID"
    echo "ID from os-release: $RREL"
    echo "installer: ${RHID}-${RREL}.sh"
    echo "### DEBUG ###"
    echo
  fi
  if [ -f ${RHID}-${RREL}.sh ]; then
    echo "copy & paste the following command to begin the install:"
    echo
    echo " bash ${RHID}-${RREL}.sh | tee installer.log 2>&1"
    echo
  else
    DEF=0
  fi
fi

if [ $LXTYPE == "DEBIAN" ]; then
  ID=`grep ^ID= /etc/os-release | awk -F\= '{ print $2 }'`
  VER=`grep ^VERSION_ID= /etc/os-release | awk -F\= '{ print $2 }'| tr -d \"`

  if [ -f ${ID}-${VER}.sh ]; then
    DEF=1
    echo "copy & paste the following command to begin the install:"
    echo
    echo " bash ${ID}-${VER}.sh | tee installer.log 2>&1"
    echo
  fi
  if [ $DBG -ne 0 ]; then
    echo
    echo "### DEBUG ###"
    echo "RVER = $RVER"
    echo "Debian or derivative detected:"
    echo "$ID version $VER"
    echo "### DEBUG ###"
    echo
  fi
 
fi

if [ $DEF == 0 ]; then
  echo "$LXTYPE type system detected, you can try the installer for the"
  echo "distro closest to yours, or refer to manual-install.txt to proceed"
fi


